# frontend/Dockerfile
FROM node:22.13.1

# 작업 디렉토리 설정
WORKDIR /app

# package.json과 package-lock.json을 먼저 복사
COPY package*.json .

# # 의존성 설치
RUN npm install

# 나머지 애플리케이션 소스 코드 복사
COPY . .

# 컨테이너가 시작될 때 실행될 명령어 설정
# CMD ["tail", "-f", "/dev/null"]
CMD ["npm", "run", "dev"]