"""auto_migration_20250218_130614

Revision ID: 38dc1e16b382
Revises: 85ae030f101e
Create Date: 2025-02-18 13:06:15.672916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38dc1e16b382'
down_revision: Union[str, None] = '85ae030f101e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'note', 'discussion', ['discussion_pk'], ['discussion_pk'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    # ### end Alembic commands ###
