"""auto_migration_20250220_194149

Revision ID: f0972280f48c
Revises: 38dc1e16b382
Create Date: 2025-02-20 19:41:53.205278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0972280f48c'
down_revision: Union[str, None] = '38dc1e16b382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discussion', 'is_active')
    # ### end Alembic commands ###
